spring:
  application:
    name: spring-eureka-producer

server:
  port: 9000
  

eureka:
  instance:
    hostname: producer
    status-page-url: http://localhost:9000/info    
    health-check-url: http://localhost:9000/health
  client:
    service-url:
      defaultZone: http://localhost:9030/eureka/