server:
  port: 9030

spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eurekaserver3
  client:
    service-url:
      defaultZone: http://eurekaserver2:9010/eureka # eureka 服务器的地址
