server:
  port: 8010
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lfeiniao/spring-cloud-eureka.git    # 配置git仓库的地址
          search-paths: configrepo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 379944104@qq.com                                         # git仓库的账号
          password: 2012liuyang                                          # git仓库的密码